[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/src/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
